version: '3.4'

services:
  jdk: 
    build:
      context: .docker
    restart: always
    volumes:
      - .:/myapp
      - root:/root
    networks:
      - java

  tomcat:
    image: tomcat:11.0-jdk21
    ports: [8090:8090]
    volumes:
      - ./.docker/server.xml:/usr/local/tomcat/conf/server.xml
    networks:
      - java

networks:
  java:

volumes:
  root:

# mysql:
#     image: mysql:8.0
#     ports:
#       - "3306:3306"
#     environment:
#       - MYSQL_ROOT_PASSWORD=
#       - MYSQL_ALLOW_EMPTY_PASSWORD=true
#       - MYSQL_USER=petclinic
#       - MYSQL_PASSWORD=petclinic
#       - MYSQL_DATABASE=petclinic
#     volumes:
#       - "./conf.d:/etc/mysql/conf.d:ro"
#     profiles:
#     - mysql
#   postgres:
#     image: postgres:15.3
#     ports:
#       - "5432:5432"
#     environment:
#       - POSTGRES_PASSWORD=petclinic
#       - POSTGRES_USER=petclinic
#       - POSTGRES_DB=petclinic
#     profiles:
#     - postgres